name: stacked_core
description: Shared code between the stacked packages.
version: 1.2.4
homepage: https://stacked.filledstacks.com/
repository: https://github.com/Stacked-Org/core.git
issue_tracker: https://github.com/Stacked-Org/framework/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  get_it: ^7.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
